### ISSUE TITLE
unable to start node/miner

### ISSUE THREAD

**Issue by n4kashu** [inescoin/inescoin-blockchain#1]
hi, as there is no documentation I have digged in..

I was ableto build the dockercompose only after removing the messenger part as it was referencing something that is not awailable on git.
also dependency to explorer is there in the build
anyway, I have connected to the blockchain container and found the binaries.. something there...

root@blockchain:/opt/src/bin# l
total 20
-rwxr-xr-x 1 root root  887 Sep  8 06:03 inescoin-miner
-rwxr-xr-x 1 root root 6311 Sep  8 06:03 inescoin-node
drwxr-xr-x 2 root root 4096 Sep  8 06:03 .
drwxr-xr-x 4 root root 4096 Sep  8 06:03 ..
root@blockchain:/opt/src/bin# ./inescoin-node
PHP Warning:  require(/opt/src/bin/../../vendor/autoload.php): failed to open stream: No such file or directory in /opt/src/bin/inescoin-node on line 8
PHP Fatal error:  require(): Failed opening required '/opt/src/bin/../../vendor/autoload.php' (include_path='.:/usr/share/php') in /opt/src/bin/inescoin-node on line 8
root@blockchain:/opt/src/bin#
 please advice/create basic documentation.

**Comment by xunppchen** [comment]
hi, I also got the error message:
PHP Fatal error:  Uncaught Error: Call to a member function getHeight() on null in /opt/src/core/Blockchain.php:400
Stack trace:
#0 /opt/src/core/Node/P2pServer.php(630): Inescoin\Blockchain->bulkAdd(Array)
#1 /opt/src/core/Node/P2pServer.php(99): Inescoin\Node\P2pServer->handlePeerBlockSyncResponse(Object(Inescoin\Node\Packet), Object(React\Socket\Connection))
#2 /opt/vendor/evenement/evenement/src/Evenement/EventEmitterTrait.php(123): Inescoin\Node\P2pServer->Inescoin\Node\{closure}('x01500022000220...')
#3 /opt/vendor/react/stream/src/Util.php(71): Evenement\EventEmitter->emit('data', Array)
#4 /opt/vendor/evenement/evenement/src/Evenement/EventEmitterTrait.php(123): React\Stream\Util::React\Stream\{closure}('x01500022000220...')
#5 /opt/vendor/react/stream/src/DuplexResourceStream.php(193): Evenement\EventEmitter->emit('data', Array)
#6 /opt/vendor/react/event-loop/src/StreamSelectLoop.php(244): React\Stream\DuplexResourceStream->handleData(Resource id #366)
#7 /opt/vendor/react/event-loop/src/StreamSelectLoop.php(211): Re in /opt/src/core/Blockchain.php on line 400

**Comment by mounirrquiba** [comment]
@n4kashu you can use this instructions to start Inescoin node

```
  # With service
  systemctrl start inescoin-node.service
  
  # With bin
  cd /opt/
  src/bin/inescoin-node --rpc-bind-port=8087 --p2p-bind-port=3031 --network=MAINNET --prefix=moon --rpc-bind-ip=IP --p2p-bind-ip=IP
  
```

**Comment by mounirrquiba** [comment]
@xunppchen Thanks for your report, commit 9ef7b6621ff283b72685987c6cc995b0827181b8 fixed this issue

**Comment by xunppchen** [comment]
Thank you, Sir,
I have an other error when i deploy a new service with new git :









*ERROR! role definitions must contain a role nameThe error appears to be in
'/home/ubuntu/inescoin-ansible/inescoin.yml': line 19, column 5, but maybe
elsewhere in the file depending on the exact syntax problem.The offending
line appears to be:  - group:    ^ here*

mounirrquiba <notifications@github.com> 于2019年9月9日周一 下午11:48写道：
