### ISSUE TITLE
restricted to mine only for few addresses?

### ISSUE THREAD

**Issue by n4kashu** [inescoin/inescoin-blockchain#2]
HI,

I have managed to start the chain, miner and so on but there is something odd.. it allows to mine only to few selected addresses?

string(44) "Block submitted ok, start blockchain push..."
string(306) "ERROR: [coinbase] Invalid address =>0xbF893c813c155c92C8De1C3D6Ed2AD75f355873c excepeted => 0x9c7983ae76A0371fFce50Df3383eF53Dea0647b8|0x5967a4016501465CD951a1e3984F772AfDeB5207|0x8Fa2F8342E34cb63d78eb76415857B4a7Cd767Cd|0x3D3C7Ee05174c93356CA85aF54Fff0Ec551A805B|0xECAF3Ec27506E2e718e3e4dfb3a6B105284bBF2E"
string(24) "ERROR: Invalid transfers"

**Comment by n4kashu** [comment]
these addresses are hardcoded in blockchainConfig as eligible miners.... wtf?

**Comment by mounirrquiba** [comment]
Hello, 
Yes, version 1.0 is centralized miners,
I will update readme file with "How to create your own Blockchain with inescoin fork" with very quick steps

Thanks
